Prism CChair[5];
int Cseat[4][3]={	{-40,40,60},
			{ 40,40,60},
			{ 40,-40,60},
			{-40,-40,60}};
int Cseat2[4][3];
int Cseatv[1];
int Cseatsurface[1][SURFSIZE]={{cCHAIR,4,3,2,1,0}};

int Carmleft[4][3]={{-50,40,90},
		{-40, 40, 60},
		{-40,-40, 60},
		{-50,-40, 90}};
int Carmleft2[4][3];
int Carmleftv[1];
int Carmleftsurface[1][SURFSIZE]={{cCHAIR,4,3,2,1,0}};

int Carmrite[4][3]={{50,40,90},
		{40, 40,60},
		{40,-40,60},
		{50,-40,90}};
int Carmrite2[4][3];
int Carmritev[1];
int Carmritesurface[1][SURFSIZE]={	{cCHAIR,4,3,2,1,0}};

int Cback[4][3]={	{-20,60,150},
			{ 20,60,150},
			{ 40,40, 60},
			{-40,40, 60}};
int Cback2[4][3];
int Cbackv[2];
int Cbacksurface[2][SURFSIZE]={{cCHAIR,4,3,2,1,0},
				{cCHAIR,4,0,1,2,3}};

int Cbase[8][3]={	{-5, 5,   0},
			{ 5, 5,   0},
			{ 5,-5,   0},
			{-5,-5,   0},
			{-5, 5,60},
			{ 5, 5,60},
			{ 5,-5,60},
			{-5,-5,60}};

int Cbase2[8][3];
int Cbasev[4];
int Cbasesurface[4][SURFSIZE]={{cCHAIRBASE,4,0,3,7,4},
				{cCHAIRBASE,4,3,2,6,7},
				{cCHAIRBASE,4,1,0,4,5},
				{cCHAIRBASE,4,2,1,5,6}};
