
Prism Snoopparts[2];
int sAbdomen[4][3]={{	  0, 100,  0},
			{  -180,   0,  0},
			{	  0,-100,  0},
			{ 	  0,   0, 70}};
int sAbdomen2[4][3];
int sAbdomenv[2];

int sAbdomensurface[2][SURFSIZE]={{cTOPSNOOP,3,0,1,3,0},
				{cTOPSNOOP,3,2,3,1,2}};
							

int sHead[4][3]={ {	  0, 100,  0},
		{   150,   0,  0},
		{	  0,-100,  0},
		{ 	  0,   0, 70}};
int sHead2[4][3];
int sHeadv[3];

int sHeadsurface[3][SURFSIZE]={	{cTOPSNOOP,3,0,3,1,0},
				{cTOPSNOOP,3,2,1,3,2},
				{cBOTTOMSNOOP,3,0,1,2,0}};

