/*----------------------------------*
 * The Colony
 * Copyright 1988 by David A. Smith
 * All Rights Reserved
 * David A. Smith
 * 111 Gold Meadow Dr.
 * Cary, NC 27513
 * (919) 469-8485
 *----------------------------------*/
#define EXT extern
#include "gamedefs.h"

char lsColor[MAXROB_COLOR][6]=
/* cCLEAR	0  */{{CLEAR,vBLACK,vBLACK,vBLACK,vBLACK,1},
/* cBLACK	1  */{BLACK,vBLACK,vBLACK,vBLACK,vBLACK,1},
/* cBLUE  	2  */{GRAY,vBLACK,vBLUE,vBLUE,vBLUE,1},	
/* cGREEN	3  */{LTGRAY,vBLACK,vGREEN,vGREEN,vGREEN,1},
/* cCYAN  	4  */{GRAY,vBLACK,vCYAN,vCYAN,vCYAN,1},	
/* cRED	 	5  */{GRAY,vBLACK,vRED,vRED,vRED,1},	
/* cMAGENTA	6  */{GRAY,vBLACK,vMAGENTA,vMAGENTA,vMAGENTA,1},
/* cBROWN	7  */{DKGRAY,vBLACK,vBROWN,vBROWN,vBROWN,1},
/* cWHITE	8  */{WHITE,vBLACK,vWHITE,vWHITE,vWHITE,1},
/* cDKGRAY	9  */{DKGRAY,vBLACK,vDKGRAY,vDKGRAY,vDKGRAY,1},
/* cLTBLUE 	10 */{GRAY,vBLACK,vLTBLUE,vLTBLUE,vLTBLUE,1},
/* cLTGREEN	11 */{LTGRAY,vBLACK,vLTGREEN,vLTGREEN,vLTGREEN,1},
/* cLTCYAN  	12 */{LTGRAY,vBLACK,vLTCYAN,vLTCYAN,vLTCYAN,1},
/* cLTRED	13 */{LTGRAY,vBLACK,vLTRED,vLTRED,cLTRED,1},
/* cLTMAGENTA	14 */{LTGRAY,vBLACK,vLTMAGENTA,vLTMAGENTA,vLTMAGENTA,1},
/* cYELLOW	15 */{WHITE,vBLACK,vYELLOW,vYELLOW,vYELLOW,1},
/* cINTWHITE	16 */{WHITE,vBLACK,vINTWHITE,vINTWHITE,vINTWHITE,1},
/* cBATH 	17 */{WHITE,vBLACK,vINTWHITE,vINTWHITE,vBLACK,1},
/* cWATER	18 */{LTGRAY,vBLACK,vWHITE,vBLUE,vBLUE,4},
/* cSILVER	19 */{LTGRAY,vBLACK,vWHITE,vINTWHITE,vBLUE,3},
/* cREACTOR	20 */{WHITE,vBLACK,vWHITE,vWHITE,vWHITE,1},
/* cBLANKET	21 */{GRAY,vBLACK,vGREEN,vWHITE,vGREEN,3},
/* cSHEET	22 */{WHITE,vBLACK,vINTWHITE,vINTWHITE,vINTWHITE,1},
/* cBED		23 */{DKGRAY,vBLACK,vBROWN,vRED,vBROWN,4},
/* cBOX		24 */{GRAY,vBLACK,vBROWN,vWHITE,vBROWN,3},
/* cBENCH	25 */{GRAY,vBLACK,vBROWN,vBROWN,vBROWN,1},
/* cCHAIR	26 */{LTGRAY,vBLUE,vLTBLUE,vWHITE,vBLUE,3},
/* cCHAIRBASE	27 */{DKGRAY,vBLUE,vBLUE,vLTBLUE,vBLUE,3},
/* cCOUCH	28 */{GRAY,vBLACK,vRED,vCYAN,vRED,3}, 
/* cCONSOLE	29 */{LTGRAY,vBLACK,vBROWN,vRED,vRED,3},
/* cTV		30 */{GRAY,vBLACK,vBROWN,vWHITE,vBROWN,3},
/* cTVSCREEN	31 */{DKGRAY,vDKGRAY,vDKGRAY,vWHITE,DKGRAY,1},
/* cDRAWER	32 */{GRAY,vBLACK,vBROWN,vWHITE,vBROWN,3},
/* cCRYO	33 */{GRAY,vBLUE,vLTBLUE,vINTWHITE,vBLUE,3},
/* cCRYOGLASS	34 */{LTGRAY,vBLUE,vINTWHITE,vLTBLUE,vBLUE,3},
/* cCRYOBASE	35 */{DKGRAY,vBLUE,vBLUE,vLTBLUE,vBLUE,3},
/* cCUBE	36 */{LTGRAY,vBLACK,vCYAN,vINTWHITE,vCYAN,3},
/* cDESK	37 */{GRAY,vBLACK,vBROWN,vWHITE,vBROWN,3},
/* cDESKTOP	38 */{DKGRAY,vBLACK,vBROWN,vBROWN,vBROWN,1},
/* cDESKCHAIR	39 */{LTGRAY,vBLACK,vGREEN,vDKGRAY,vGREEN,3},
/* cMAC		40 */{WHITE,vBLACK,vINTWHITE,vINTWHITE,vBLACK,1},
/* cMACSCREEN	41 */{DKGRAY,vBLACK,vDKGRAY,vDKGRAY,vDKGRAY,1},
/* cDRONE	42 */{LTGRAY,vBLACK,vCYAN,vCYAN,vBLACK,1},
/* cCLAW1	43 */{DKGRAY,vBLACK,vRED,vRED,vRED,1},
/* cCLAW2	44 */{LTGRAY,vBLACK,vCYAN,vCYAN,vCYAN,1},
/* cEYES	45 */{WHITE,vINTWHITE,vINTWHITE,vINTWHITE,vINTWHITE,1},
/* cEYE		46 */{WHITE,vINTWHITE,vINTWHITE,vINTWHITE,vINTWHITE,1},
/* cIRIS	47 */{LTGRAY,vBLACK,vBLUE,vWHITE,vBLUE,3},
/* cPUPIL	48 */{BLACK,vBLACK,vBLACK,vBLACK,vBLACK,3},
/* cFORKLIFT    49 */{LTGRAY,vBLACK,vYELLOW,vBROWN,vYELLOW,3},
/* cTREAD1	50 */{DKGRAY,vBLACK,vYELLOW,vBROWN,vYELLOW,4},
/* cTREAD2	51 */{DKGRAY,vBLACK,vYELLOW,vBROWN,vYELLOW,5},
/* cPOT		52 */{GRAY,vBLACK,vBROWN,vBROWN,vBROWN,1},
/* cPLANT	53 */{GRAY,vGREEN,vGREEN,vGREEN,vGREEN,1},
/* cPOWER	54 */{LTGRAY,vBLUE,vLTBLUE,vWHITE,vBLUE,3},
/* cPBASE	55 */{DKGRAY,vBLUE,vLTBLUE,vWHITE,vBLUE,3},
/* cPSOURCE	56 */{GRAY,vRED,vRED,vYELLOW,vRED,3},
/* cPYRAMID	57 */{GRAY,vBLACK,vRED,vINTWHITE,vRED,3},
/* cQUEEN	58 */{GRAY,vYELLOW,vYELLOW,vINTWHITE,vYELLOW,3},
/* cTOPSNOOP	59 */{GRAY,vMAGENTA,vCYAN,vMAGENTA,vCYAN,3},
/* cBOTTOMSNOOP	60 */{DKGRAY,vMAGENTA,vDKGRAY,vMAGENTA,vMAGENTA,3},
/* cTABLE	61 */{GRAY,vBROWN,vBROWN,vWHITE,vBROWN,3},
/* cTABLEBASE	62 */{DKGRAY,vBROWN,vBROWN,vDKGRAY,vBROWN,3},
/* cPSTAND	63 */{DKGRAY,vBLACK,vMAGENTA,vMAGENTA,vMAGENTA,1},
/* cPLENS	64 */{BLACK,vBLACK,vBLACK,vBLACK,vBLACK,1},
/* cPROJECTOR	65 */{GRAY,vBLACK,vCYAN,vCYAN,vCYAN,1},
/* cTELE	66 */{LTGRAY,vRED,vDKGRAY,vWHITE,vRED,3},
/* cTELEDOOR	67 */{LTGRAY,vBLACK,vWHITE,vINTWHITE,vBLUE,3},
/* cUPYRAMID	68 */{LTGRAY,vBLACK,vLTBLUE,vINTWHITE,vBLUE,3},
/* cROCK	69 */{GRAY,vRED,vRED,vRED,vRED,1},
/* cCOLONY	70 */{GRAY,vYELLOW,vYELLOW,vYELLOW,vYELLOW,1},
/* cCDOOR	71 */{GRAY,vYELLOW,vYELLOW,vYELLOW,vYELLOW,1},
/* cSHIP	72 */{GRAY,vLTBLUE,vLTBLUE,vLTBLUE,vLTBLUE,1},
/* cPROJ	73 */{GRAY,vCYAN,vCYAN,vCYAN,vCYAN,1},
/* cSHADOW	74 */{DKGRAY,vDKGRAY,vDKGRAY,vDKGRAY,vDKGRAY,1},
/* cLTGRAY	75 */{LTGRAY,vDKGRAY,vDKGRAY,vINTWHITE,vDKGRAY,3},
/* cGRAY	76 */{GRAY,vDKGRAY,vDKGRAY,vWHITE,vDKGRAY,3},
/* cWALL	77 */{WHITE,vBLACK,vWHITE,vWHITE,vBLACK,3},
/* cQUEEN2	78 */{GRAY,vBLACK,vINTWHITE,vINTWHITE,vBLACK,3}};

/*		79 */
/* cRAINBOW1	80 */
/* cRAINBOW2	81 */ 
/* cRAINBOW3	82 */
/* cRAINBOW4	83 */
/* cRAINBOW5	84 */

